# Generated by Django 5.1.3 on 2024-11-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='exp_required',
            field=models.IntegerField(default=150),
        ),
    ]
