# Generated by Django 5.1.3 on 2024-11-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skills_exp_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
